[package]
name = "golem-wasm-rpc-stubgen"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/wasm-rpc"
description = "Golem WASM RPC stub generator"

[features]
unstable-dec-dep = []

[lib]
name = "golem_wasm_rpc_stubgen"
path = "src/lib.rs"
harness = false

[[bin]]
name = "wasm-rpc-stubgen"
path = "src/main.rs"
test = false

[[test]]
name = "wit"
harness = false

[[test]]
name = "add_dep"
harness = false

[dependencies]
anyhow = "1.0.79"
assert2 = "0.3.15"
cargo_toml = "0.20.2"
clap = { version = "4.5.7", features = ["derive"] }
colored = "2.1.0"
cargo-component-core = "=0.13.2"
cargo-component = "=0.13.2"
dir-diff = "0.3.3"
fs_extra = { workspace = true }
glob = "0.3.1"
golem-wasm-ast = { workspace = true }
golem-wasm-rpc = { path = "../wasm-rpc", version = "0.0.0" }
heck = "0.5.0"
id-arena = "2.2.1"
indexmap = "2.2.6"
itertools = "0.12.1"
pretty_env_logger = "0.5.0"
prettyplease = "0.2.20"
proc-macro2 = "1.0.85"
quote = "1.0.36"
regex = "1.10.4"
semver = "1.0.23"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.128"
serde_yaml = "0.9.33"
syn = "2.0.66"
tempfile = { workspace = true }
tokio = { workspace = true }
toml = "0.8.14"
walkdir = "2.5.0"
wac-graph = "=0.6.0"
wit-bindgen-rust = "=0.26.0"
# wit-encoder = "=0.219.0"
wit-encoder = { git = "https://github.com/golemcloud/wasm-tools.git", rev = "46b168c169dc28d169d60e60ddbe4eed20f905b3"}
# wit-encoder = { path = "../../wasm-tools/crates/wit-encoder"}
# wit-parser = "=0.219.0"
wit-parser = { git = "https://github.com/golemcloud/wasm-tools.git", rev = "46b168c169dc28d169d60e60ddbe4eed20f905b3"}

# wit-parser = { path = "../../wasm-tools/crates/wit-parser"}


[dev-dependencies]
test-r = { workspace = true }