[package]
name = "golem-wasm-rpc-stubgen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "golem-wasm-rpc-stubgen"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.79"
cargo_toml = "0.19.1"
clap = "4.4.18"
heck = "0.4.1"
id-arena = "2.2.1"
indexmap = "2.0.0"
prettyplease = "0.2.16"
proc-macro2 = "1.0.78"
quote = "1.0.35"
serde = { version = "1.0.196", features = ["derive"] }
syn = "2.0.48"
toml = "0.8.10"
wit-bindgen-rust = "0.17.0"
wit-parser = "0.13.2"
