[package]
name = "golem-wasm-rpc-stubgen"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/wasm-rpc"
description = "Golem WASM RPC stub generator"

[lib]
name = "golem_wasm_rpc_stubgen"
path = "src/lib.rs"

[[bin]]
name = "wasm-rpc-stubgen"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.79"
cargo_toml = "0.20.2"
clap = { version = "4.5.7", features = ["derive"] }
cargo-component-core = "=0.13.2"
cargo-component = "=0.13.2"
dir-diff = "0.3.3"
fs_extra = "1.3.0"
golem-wasm-ast = "1.0.0"
golem-wasm-rpc = { path = "../wasm-rpc", version = "0.0.0" }
heck = "0.5.0"
id-arena = "2.2.1"
indexmap = "2.2.6"
pretty_env_logger = "0.5.0"
prettyplease = "0.2.20"
proc-macro2 = "1.0.85"
quote = "1.0.36"
regex = "1.10.4"
serde = { version = "1.0.203", features = ["derive"] }
syn = "2.0.66"
tempfile = "3.12.0"
tokio = "1.38.0"
toml = "0.8.14"
wasm-compose = "0.207.0"
wit-bindgen-rust = "=0.26.0"
wit-parser = "0.207.0"
