[package]
name = "golem"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud/"
repository = "https://github.com/golemcloud/golem-cli"
readme = "README.md"
description = "Single Golem executable for testing"

[lib]
harness = false

[[bin]]
name = "golem"
path = "src/main.rs"
test = false

[dependencies]
golem-cli = { path = "../golem-cli", version = "=0.0.0" }

golem-common = { workspace = true }
golem-component-compilation-service = { workspace = true }
golem-component-service = { workspace = true }
golem-component-service-base = { workspace = true }
golem-service-base = { workspace = true }
golem-shard-manager = { workspace = true }
golem-worker-executor = { workspace = true }
golem-worker-executor-base = { workspace = true }
golem-worker-service = { workspace = true }
golem-worker-service-base = { workspace = true }

anyhow = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
dirs = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
futures = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-prometheus = { workspace = true }
opentelemetry_sdk = { workspace = true }
poem = { workspace = true }
prometheus = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
test-r = { workspace = true }
